apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: chat-server
spec:
  gateways:
  - server-gateway
  hosts:
  - chat-server.apps.atlanta-5d16.openshiftworkshop.com
  http:
  - route:
    - destination:
        host: chat-server
        subset: all
      weight: 100
