apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis-v1
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: redis
        version: v1
    spec:
      containers:
      - env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              key: database-password
              name: redis
        name: redis
        image: registry.access.redhat.com/rhscl/redis-32-rhel7
        imagePullPolicy: Always
        ports:
        - containerPort: 6379
        volumeMounts:
        - mountPath: /var/lib/redis/data
          name: redis-data
      volumes:
      - emptyDir: {}
        name: redis-data
---
apiVersion: v1
data:
  database-password: cmVkaXM=
kind: Secret
metadata:
  annotations:
    template.openshift.io/expose-password: '{.data[''database-password'']}'
  labels:
    app: redis-ephemeral
    template: redis-ephemeral-template
  name: redis
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  ports:
  - name: tcp
    port: 6379
    protocol: TCP
  selector:
    app: redis
